apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: yaaiecomm
  labels:
    app: forgecommerce
    component: api
spec:
  selector:
    app: forgecommerce
    component: api
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
